labs/app-services/src/SecondChanceParts.Web/Pages/Cart/Checkout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SecondChanceParts.Web.Data;
using SecondChanceParts.Web.Models;
using Microsoft.Extensions.Configuration;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;

namespace SecondChanceParts.Web.Pages.Cart
{
    public class CheckoutModel : PageModel
    {
        private readonly SecondChanceParts.Web.Data.SecondChancePartsContext _context;
        private readonly IConfiguration _configuration;
        private string _apiUrl;

        private static readonly HttpClient _httpClient = new HttpClient();

        public CheckoutModel(SecondChanceParts.Web.Data.SecondChancePartsContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;

            _apiUrl = _configuration["AppSettings:ApiRootUrl"];
        }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cart = await GetShoppingCart(id.Value);
            await Checkout(cart);
            
            return Page();
        }

        [BindProperty]
        public SecondChanceParts.Web.Models.ShoppingCart ShoppingCart { get; set; }

        private async Task<SecondChanceParts.Web.Models.ShoppingCart> GetShoppingCart(int id){

            _httpClient.DefaultRequestHeaders.Accept.Clear();
            _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


            var response = await _httpClient.GetAsync($"{_apiUrl}/api/carts/{id}");

            if(!response.IsSuccessStatusCode){
                throw new Exception($"Shopping Cart with ID {id} not found.");
            }

            var content = await response.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
            };
            var cart = JsonSerializer.Deserialize<SecondChanceParts.Web.Models.ShoppingCart>(content,options);

            return cart;

        }
        private async Task<SecondChanceParts.Web.Models.ShoppingCart> Checkout(SecondChanceParts.Web.Models.ShoppingCart cart){

            _httpClient.DefaultRequestHeaders.Accept.Clear();
            _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            StringContent content = new StringContent(JsonSerializer.Serialize(cart));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            
            var response = await _httpClient.PostAsync($"{_apiUrl}/api/carts/{cart.CartId}/checkout",content);

            if(!response.IsSuccessStatusCode){
                var errorContent = await response.Content.ReadAsStringAsync();
                throw new Exception($"Error checking out cart: {errorContent}");
            }

            return cart;

        }


    }
}

labs/app-services/src/SecondChanceParts.Web/Pages/Cart/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SecondChanceParts.Web.Data;
using SecondChanceParts.Web.Models;

namespace SecondChanceParts.Web.Pages.Cart
{
    public class CreateModel : PageModel
    {
        private readonly SecondChanceParts.Web.Data.SecondChancePartsContext _context;

        public CreateModel(SecondChanceParts.Web.Data.SecondChancePartsContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public SecondChanceParts.Web.Models.ShoppingCart ShoppingCart { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.ShoppingCarts.Add(ShoppingCart);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

labs/app-services/src/SecondChanceParts.Web/Pages/Cart/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SecondChanceParts.Web.Data;
using SecondChanceParts.Web.Models;

namespace SecondChanceParts.Web.Pages.Cart
{
    public class DeleteModel : PageModel
    {
        private readonly SecondChanceParts.Web.Data.SecondChancePartsContext _context;

        public DeleteModel(SecondChanceParts.Web.Data.SecondChancePartsContext context)
        {
            _context = context;
        }

        [BindProperty]
        public SecondChanceParts.Web.Models.ShoppingCart ShoppingCart { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ShoppingCart = await _context.ShoppingCarts.FirstOrDefaultAsync(m => m.CartId == id);

            if (ShoppingCart == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ShoppingCart = await _context.ShoppingCarts.FindAsync(id);

            if (ShoppingCart != null)
            {
                _context.ShoppingCarts.Remove(ShoppingCart);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

labs/app-services/src/SecondChanceParts.Web/Pages/Cart/Details.cshtml.cs
using System.Reflection.Emit;
using System.Collections.Immutable;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SecondChanceParts.Web.Data;
using SecondChanceParts.Web.Models;
using Microsoft.Extensions.Configuration;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Microsoft.Extensions.Logging;

namespace SecondChanceParts.Web.Pages.Cart
{
    public class DetailsModel : PageModel
    {
        private readonly IHttpClientFactory _clientFactory;
        private readonly SecondChanceParts.Web.Data.SecondChancePartsContext _context;
        private readonly IConfiguration _configuration;
        private string _apiUrl;

        private ILogger<PageModel> _logger;

        public DetailsModel(SecondChanceParts.Web.Data.SecondChancePartsContext context, 
                            IConfiguration configuration, 
                            IHttpClientFactory clientFactory,
                            ILogger<PageModel> logger)
        {
            _context = context;
            _configuration = configuration;
            _clientFactory = clientFactory;
            _logger = logger;

            _apiUrl = _configuration["AppSettings:ApiRootUrl"];
        }

        [BindProperty]
        public SecondChanceParts.Web.Models.ShoppingCart ShoppingCart { get; set; }

        [BindProperty]
        public IList<ShoppingCartItem> ShoppingCartItems { get;set; }

        [BindProperty]
        public ShoppingCartItem NewShoppingCartItem {get;set;}

        [BindProperty]
        public IList<Part> Parts { get;set; }

        [BindProperty]
        public IList<SelectListItem> PartsList { get;set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await LoadData(id.Value);

            if (ShoppingCart == null)
            {
                return NotFound();
            }

            return Page();
        }
    
        public async Task<IActionResult> OnPostAddToCart(){

            //await _context.ShoppingCartItems.AddAsync(NewShoppingCartItem);
            //await _context.SaveChangesAsync();

            await AddToCart(NewShoppingCartItem);

            await LoadData(NewShoppingCartItem.ShoppingCartId);

            return Page();
        }

        public IActionResult OnPostCheckout(){

             return RedirectToPage("./Checkout", new {id=ShoppingCart.CartId});
        }

        private async Task LoadData(int cartId){

            
            NewShoppingCartItem = new ShoppingCartItem() {ShoppingCartId = cartId};

            ShoppingCart = await GetShoppingCart(cartId); //await _context.ShoppingCarts.FirstOrDefaultAsync(m => m.CartId == cartId);

            ShoppingCartItems = await GetShoppingCartItems(cartId); //await _context.ShoppingCartItems.Where(c => c.ShoppingCartId == cartId).ToListAsync();

            Parts = await GetParts();

            PartsList = Parts.Select(a => 
                                  new SelectListItem 
                                  {
                                      Value = a.PartId.ToString(),
                                      Text =  $"{a.Name} (${a.UnitCost})"
                                  }).ToList();

        }

        private async Task<SecondChanceParts.Web.Models.ShoppingCart> GetShoppingCart(int id){

            _logger.LogTrace($"GetShoppingCart: API URL={_apiUrl}");

            var client = _clientFactory.CreateClient();

            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            var response = await client.GetAsync($"{_apiUrl}/api/carts/{id}");

            if(!response.IsSuccessStatusCode){
                throw new Exception($"Shopping Cart with ID {id} not found.");
            }

            var content = await response.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
            };
            var cart = JsonSerializer.Deserialize<SecondChanceParts.Web.Models.ShoppingCart>(content,options);

            return cart;

        }

        private async Task<List<SecondChanceParts.Web.Models.ShoppingCartItem>> GetShoppingCartItems(int id){

            var client = _clientFactory.CreateClient();

            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


            var response = await client.GetAsync($"{_apiUrl}/api/carts/{id}/items");

            if(!response.IsSuccessStatusCode){
                throw new Exception($"Shopping Cart with ID {id} not found.");
            }

            var content = await response.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
            };
            var cart = JsonSerializer.Deserialize<List<SecondChanceParts.Web.Models.ShoppingCartItem>>(content,options);

            return cart;

        }

        private async Task<List<SecondChanceParts.Web.Models.Part>> GetParts(){

            var client = _clientFactory.CreateClient();

            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            var response = await client.GetAsync($"{_apiUrl}/api/parts");

            if(!response.IsSuccessStatusCode){
                throw new Exception($"Parts API not Found");
            }

            var content = await response.Content.ReadAsStringAsync();
            
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
            };
            var parts = JsonSerializer.Deserialize<List<SecondChanceParts.Web.Models.Part>>(content,options);

            return parts;

        }

        private async Task<SecondChanceParts.Web.Models.ShoppingCartItem> AddToCart(ShoppingCartItem item){

            var client = _clientFactory.CreateClient();

            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            StringContent content = new StringContent(JsonSerializer.Serialize(item));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            
            var response = await client.PostAsync($"{_apiUrl}/api/carts/{item.ShoppingCartId}/addtocart",content);

            if(!response.IsSuccessStatusCode){
                var errorContent = await response.Content.ReadAsStringAsync();
                throw new Exception($"Error adding to cart: {errorContent}");
            }

            return item;

        }

    }
}

labs/app-services/src/SecondChanceParts.Web/Pages/Cart/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SecondChanceParts.Web.Data;
using SecondChanceParts.Web.Models;

namespace SecondChanceParts.Web.Pages.Cart
{
    public class EditModel : PageModel
    {
        private readonly SecondChanceParts.Web.Data.SecondChancePartsContext _context;

        public EditModel(SecondChanceParts.Web.Data.SecondChancePartsContext context)
        {
            _context = context;
        }

        [BindProperty]
        public SecondChanceParts.Web.Models.ShoppingCart ShoppingCart { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ShoppingCart = await _context.ShoppingCarts.FirstOrDefaultAsync(m => m.CartId == id);

            if (ShoppingCart == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(ShoppingCart).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ShoppingCartExists(ShoppingCart.CartId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ShoppingCartExists(int id)
        {
            return _context.ShoppingCarts.Any(e => e.CartId == id);
        }
    }
}

labs/app-services/src/SecondChanceParts.Web/Pages/Cart/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SecondChanceParts.Web.Data;
using SecondChanceParts.Web.Models;

namespace SecondChanceParts.Web.Pages.Cart
{
    public class IndexModel : PageModel
    {
        private readonly SecondChanceParts.Web.Data.SecondChancePartsContext _context;

        public IndexModel(SecondChanceParts.Web.Data.SecondChancePartsContext context)
        {
            _context = context;
        }

        public IList<SecondChanceParts.Web.Models.ShoppingCart> ShoppingCart { get;set; }

        public async Task OnGetAsync()
        {
            ShoppingCart = await _context.ShoppingCarts.ToListAsync();
        }
    }
}

labs/app-services/src/SecondChanceParts.Web/Pages/Cart/Checkout.cshtml
@page
@model SecondChanceParts.Web.Pages.Cart.CheckoutModel

@{
    ViewData["Title"] = "Shopping Cart - Checkout";
}

<h1>Check Out</h1>
<hr />
<div>Thank you for submitting your order. Your order is now being processed.</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

labs/app-services/src/SecondChanceParts.Web/Pages/Cart/Create.cshtml
@page
@model SecondChanceParts.Web.Pages.Cart.CreateModel

@{
    ViewData["Title"] = "Shopping Carts";
}

<h1>Create</h1>

<h4>ShoppingCart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ShoppingCart.Username" class="control-label"></label>
                <input asp-for="ShoppingCart.Username" class="form-control" />
                <span asp-validation-for="ShoppingCart.Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShoppingCart.UserStatus" class="control-label"></label>
                <input asp-for="ShoppingCart.UserStatus" class="form-control" />
                <span asp-validation-for="ShoppingCart.UserStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShoppingCart.CartStatus" class="control-label"></label>
                <input asp-for="ShoppingCart.CartStatus" class="form-control" />
                <span asp-validation-for="ShoppingCart.CartStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

labs/app-services/src/SecondChanceParts.Web/Pages/Cart/Delete.cshtml
@page
@model SecondChanceParts.Web.Pages.Cart.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ShoppingCart</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ShoppingCart.Username)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ShoppingCart.Username)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ShoppingCart.UserStatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ShoppingCart.UserStatus)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ShoppingCart.CartStatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ShoppingCart.CartStatus)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="ShoppingCart.CartId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

labs/app-services/src/SecondChanceParts.Web/Pages/Cart/Details.cshtml
@page
@model SecondChanceParts.Web.Pages.Cart.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Shopping Cart</h1>

<div>
    <h4>Welcome  @Html.DisplayFor(model => model.ShoppingCart.Username) thank you for being a @Html.DisplayFor(model => model.ShoppingCart.UserStatus) customer!</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ShoppingCart.CartStatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ShoppingCart.CartStatus)
        </dd>
        <dt class="col-sm-2">
            Cart Total
        </dt>
        <dd class="col-sm-10">
            @Model.ShoppingCartItems.Sum(i => (i.Part.UnitCost * i.ItemCount)).ToString("0.00")
        </dd>
    </dl>
</div>
<div>
 <h4>Add Part to Shopping Cart</h4>
  <form method="post" asp-page-handler="AddToCart" >
      <input type="hidden" asp-for="NewShoppingCartItem.ShoppingCartId" />
      <table class="table">
          <tr>
              <td>
                   <div class="form-group">
                    <label class="control-label">Part</label><br>
                    <select asp-for="NewShoppingCartItem.PartId" asp-items="@Model.PartsList"></select>
                </div>
              </td>
              <td>
            <div class="form-group">
                    <label class="control-label">Units</label>
                    <input asp-for="NewShoppingCartItem.ItemCount" class="form-control" />
                </div>
              </td>
              <td>
                  <div class="form-group" style="padding-top:30px">
                     <input type="submit" value="Add To Cart" class="btn btn-primary" />
                </div>
              </td>
          </tr>
      </table>
</form>

<div>
    <h2>Shopping Cart Items</h2>
    <table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ShoppingCartItems[0].ItemId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShoppingCartItems[0].ItemCount)
            </th>
            <th>
               Part
            </th>
            <th>
                
            </th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ShoppingCartItems) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemCount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Part.Name)
                </td>
                <td>@((item.Part.UnitCost * item.ItemCount).ToString("0.00"))</td>
                <td>
                    <a asp-page="../CartItems/Delete" asp-route-id="@item.ItemId">Delete</a>
                </td>
            </tr>
        }
        </tbody>
        <tr>
            <td></td>
            <td></td>
            <td style="align:right">Total:</td>
            <td>@Model.ShoppingCartItems.Sum(i => (i.Part.UnitCost * i.ItemCount)).ToString("0.00")</td>
            <td> <form method="post">
                     <input type="hidden" asp-for="ShoppingCart.CartId" />
                    <input type="submit" asp-page-handler="Checkout" value="Check Out" class="btn btn-primary" />
                 </form>
            </td>
        </tr>
    </table>

</div
<div>
    <a asp-page="./Edit" asp-route-id="@Model.ShoppingCart.CartId">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

labs/app-services/src/SecondChanceParts.Web/Pages/Cart/Edit.cshtml
@page
@model SecondChanceParts.Web.Pages.Cart.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ShoppingCart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ShoppingCart.CartId" />
            <div class="form-group">
                <label asp-for="ShoppingCart.Username" class="control-label"></label>
                <input asp-for="ShoppingCart.Username" class="form-control" />
                <span asp-validation-for="ShoppingCart.Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShoppingCart.UserStatus" class="control-label"></label>
                <input asp-for="ShoppingCart.UserStatus" class="form-control" />
                <span asp-validation-for="ShoppingCart.UserStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShoppingCart.CartStatus" class="control-label"></label>
                <input asp-for="ShoppingCart.CartStatus" class="form-control" />
                <span asp-validation-for="ShoppingCart.CartStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

labs/app-services/src/SecondChanceParts.Web/Pages/Cart/Index.cshtml
@page
@model SecondChanceParts.Web.Pages.Cart.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.ShoppingCart[0].Username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShoppingCart[0].UserStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShoppingCart[0].CartStatus)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.ShoppingCart) {
        <tr>
            <td>
                <a asp-page="./Details" asp-route-id="@item.CartId">Open Cart</a> 
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CartStatus)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.CartId">Edit</a> |
                <a asp-page="./Delete" asp-route-id="@item.CartId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>